---

- name: install nf-core
  local_action:
    module: pip
    virtualenv_command: /lupus/ngi/irma3/virtualenv-15.0.0/virtualenv.py
    virtualenv: "{{ nf_core_env }}"
    name: nf-core
    state: present

- name: Download NextFlow
  local_action:
    get_url url="{{ nextflow_download_url }}" dest="{{ nf_core_env }}/bin" mode="u+rwx,g=rwx"

- name: Install NextFlow
  local_action:
    module: command
    _raw_params: "{{ nf_core_env }}/bin/nextflow"
  environment:
    NXF_LAUNCHER: "/scratch"
    NXF_HOME: "{{ nf_core_env }}/nextflow"
    NXF_WORK: "/scratch"

- name: Create temp directories for singularity images
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ ngi_containers }}/singularity_cache"
    - "{{ ngi_containers }}/singularity_temp"

- name: Checking existing containers
  find:
    paths: "{{ ngi_containers }}"
    file_type: file
    patterns:  '^nf-core-.*-[0-9]\.[0-9]\.[0-9]\.simg'
    use_regex: yes
    recurse: yes
  register: check_containers

- name: Add to existing containers
  no_log: true
  set_fact:
    existing_containers: "{{ existing_containers + [item.path.split('/')[-1]] }}"
  with_items: "{{ check_containers.files }}"

- name: nf-core
  command: "{{ nf_core_env }}/bin/nf-core -v download {{ item.name }}
   {% if 'nf-core-'+item.name+'-'+ item.release|string +'.simg' not in existing_containers %} --singularity {% endif %}
   --compress none --outdir {{ sw_path }}{{ item.name }} --release {{ item.release }}"
  environment:
    PATH: "{{ nf_core_env }}/bin:{{ ansible_env.PATH }}"
    SINGULARITY_CACHEDIR: "{{ ngi_containers }}/singularity_cache"
    SINGULARITY_TMPDIR: "{{ ngi_containers }}/singularity_temp"
  args:
    chdir: "{{ sw_path }}"
  with_items: "{{ pipelines }}"

- name: Create directories for singularity images
  file:
    path: "{{ ngi_containers }}/{{ item.name }}"
    state: directory
    mode: g+s
  with_items: "{{ pipelines }}"

- name: Copy singularity images
  copy:
     src: "{{ sw_path }}{{ item.name }}/singularity-images/nf-core-{{ item.name }}-{{ item.release }}.simg"
     dest: "{{ ngi_containers }}/{{ item.name }}/nf-core-{{ item.name }}-{{ item.release }}.simg"
     group: ngi
     mode: u=rwx,g=rwx,o=rx
  when: "{{ 'nf-core-'+item.name+'-'+ item.release|string +'.simg' not in existing_containers }}"
  with_items:
    - "{{ pipelines }}"

- name: Remove downloaded singularity images
  file:
    path: "{{ sw_path }}{{ item.name }}/singularity-images/nf-core-{{ item.name }}-{{ item.release }}.simg"
    state: absent
  with_items: "{{ pipelines }}"

- name: Remove singularity cache directories
  file: name="{{ item }}" state=absent
  with_items:
  - "{{ ngi_containers }}/singularity_cache"
  - "{{ ngi_containers }}/singularity_temp"

- name: Create nf-core config
  template:
    src: "site.config.j2"
    dest: "{{ ngi_pipeline_conf }}/{{ item.0.name }}_{{ item.1.site }}.config"
  with_nested:
  - "{{ pipelines }}"
  - [ { site: "sthlm", project_id: "{{ ngi_pipeline_sthlm_delivery }}" }, { site: "upps", project_id: "{{ ngi_pipeline_upps_delivery }}" }]

- name: Set alias for pipeline
  lineinfile:
    dest: "{{ ngi_pipeline_conf }}/{{ item.1.script }}"
    line: >
          alias {{ item.0.name }}='nextflow run {{ sw_path }}{{ item.0.name }}/workflow/ \
          -profile uppmax \
          -c {{ ngi_pipeline_conf }}/nextflow_irma_{{ item.1.site }}.config \
          -c {{ ngi_pipeline_conf }}/{{ item.0.name }}_{{ item.1.site }}.config'
    backup: no
  with_nested:
  - "{{ pipelines }}"
  - [ { site: "sthlm", script: "{{ bash_env_sthlm_script }}" }, { site: "upps", script: "{{ bash_env_upps_script }}" } ]

- name: Download SILVA classifier data for ampliseq
  get_url:
    url: https://www.arb-silva.de/fileadmin/silva_databases/qiime/Silva_132_release.zip
    dest: "{{ ngi_containers }}/ampliseq/Silva_132_release.zip"
  when: item.name == "ampliseq"
  with_items:
  - "{{ pipelines }}"

- name: Store tool version in deployment
  lineinfile:
    dest: "{{ deployed_tool_versions }}"
    line: "{{ item.name }}: {{ item.release }}"
  with_items:
  - "{{ pipelines }}"
