---
neutronstar_repo: "https://github.com/nf-core/neutronstar"
neutronstar_dest: "{{ sw_path }}/neutronstar"
# neutronstar_container_url: "docker://nf-core/neutronstar:{{ rnaseq_version }}"
neutronstar_container_path: "{{ ngi_containers }}/neutronstar"
# neutronstar_image: "neutronstar-{{ neutronstar_version }}.simg"
neutronstar_version: "1.0.0"

# Temporary variables whilst under dev by Remi
neutronstar_container_url: "docker://nfcore/neutronstar"
neutronstar_image: "neutronstar.simg"

supernova_container_url: "docker://nfcore/supernova"
supernova_image: "supernova.simg"
supernova_version: "2.1.1"
supernova_container_path: "{{ ngi_containers }}/supernova"
