---
- include: dependencies.yml

- name: Fetch ngi_reports from github
  git: repo="{{ ngi_reports_repo }}"
       dest="{{ ngi_reports_dest }}"
       version="{{ ngi_reports_version }}"
       force=yes
       recursive=yes

- name: Install ngi_reports
  shell: "{{ sw_path }}/anaconda/envs/{{ NGI_venv_py3_name }}/bin/pip install -e ."
  args:
    chdir: "{{ ngi_reports_dest }}"


- name: Create ngi_reports conf file
  template: src="ngi_reports_sthlm.conf.j2" dest="{{ ngi_pipeline_conf }}/ngi_reports_sthlm.conf"

- name: Export NGI_REPORTS_CONFIG via sourceme_sthlm
  lineinfile: dest="{{ ngi_pipeline_conf }}/{{ bash_env_sthlm_script }}"
              line='export NGI_REPORTS_CONFIG={{ ngi_pipeline_conf }}/ngi_reports_sthlm.conf'
              backup=no

- name: Set alias for regenerating project summary report
  lineinfile:
    dest: "{{ ngi_pipeline_conf }}/{{ bash_env_sthlm_script }}"
    line: >
          alias make_report='ngi_reports project_summary -md'
    backup: no

- name: Store ngi_reports tool version in deployment
  lineinfile:
    dest: "{{ deployed_tool_versions }}"
    line: "{{ item.tool_name }}: {{ item.tool_version }}"
  with_items:
    - { tool_name: "ngi_reports", tool_version: "{{ ngi_reports_version }}" }
    - { tool_name: "ngi_visualizations", tool_version: "{{ ngi_visual_version }}" }
