---

- name: create virtual python env for archive-upload
  shell: "{{ conda_bin }} create --name archive-upload python=2.7"
  args: 
    creates: "{{ archive_upload_env_root }}"

- name: get archive-upload from git
  git:
    repo: "{{ archive_upload_repo }}"
    dest: "{{ archive_upload_src_path }}"
    version: "{{ archive_upload_version }}"

- name: install archive-upload requirements
  pip:
    requirements: "{{ archive_upload_src_path }}/requirements/prod"
    chdir: "{{ archive_upload_src_path }}"
    virtualenv: "{{ archive_upload_env_root }}"
    state: present
    extra_args: "-U"

- name: install archive-upload
  pip:
    name: .
    chdir: "{{ archive_upload_src_path }}"
    virtualenv: "{{ archive_upload_env_root }}"
    state: present
    extra_args: "-U"

