---

- name: Fetch sarek from GitHub
  git: repo="{{ sarek_repo }}"
       dest="{{ sarek_dest }}"
       version="{{ sarek_version }}"
       force=yes

- name: Create sarek Singularity folder and temp/cache for images
  file: name="{{ item }}" state=directory mode=g+s
  with_items:
  - "{{ sarek_singularity }}/singularity_cache"
  - "{{ sarek_singularity }}/singularity_temp"

- name: Pull sarek Singularity images
  command: "singularity build {{ item }}-{{ sarek_version }}.img {{ sarek_singularity_repo }}/{{ item }}:{{ sarek_version }}"
  environment:
    SINGULARITY_CACHEDIR: "{{ sarek_singularity }}/singularity_cache"
    SINGULARITY_TMPDIR: "{{ sarek_singularity }}/singularity_temp"
  args:
    chdir: "{{ sarek_singularity }}"
    creates: "{{ item }}-{{ sarek_version }}.img"
  with_items: "{{ sarek_singularity_images }}"
  ignore_errors: true

- name: Remove sarek singularity temp directories
  file: name="{{ item }}" state=absent
  with_items:
  - "{{ sarek_singularity }}/singularity_cache"
  - "{{ sarek_singularity }}/singularity_temp"

- name: Create sarek site config
  template:
    src: "sarek_site.config"
    dest: "{{ ngi_pipeline_conf }}/sarek_{{ item.site }}.config"
  with_items:
  - { site: "sthlm", project_id: "{{ ngi_pipeline_sthlm_delivery }}", container_path: "{{ sarek_singularity }}" }
  - { site: "upps", project_id: "{{ ngi_pipeline_upps_delivery }}", container_path: "{{ sarek_singularity }}" }

- name: Create sarek wrapper function
  template:
    src: "sarek_exec_site.sh.j2"
    dest: "{{ ngi_resources }}/sarek_exec_{{ item.site }}.sh"
  with_items:
  - { site: "sthlm" }
  - { site: "upps" }

- name: Source sarek wrapper function
  lineinfile: dest="{{ ngi_pipeline_conf }}/{{ item.script }}"
              line="source {{ ngi_resources }}/sarek_exec_{{ item.site }}.sh"
              backup=no
  with_items:
  - { site: "sthlm", script: "{{ bash_env_sthlm_script }}" }
  - { site: "upps", script: "{{ bash_env_upps_script }}" }
