---
methylseq_repo: "https://github.com/nf-core/methylseq.git"
methylseq_dest: "{{ sw_path }}/methylseq"
methylseq_container_url: "docker://nfcore/methylseq"
methylseq_container_path: "{{ ngi_containers }}/methylseq"
methylseq_version: "1.1"
