# Omitted due to installation complications
# qatools_repo: "https://github.com/vezzi/qaTools.git"
# qatools_dest: "{{ sw_path }}/qaTools" 
# qatools_version: "0af6b1df4a51518483fa8579be8b54219802a0e7"

nougat_frc_source: "shub://remiolsen/FRCbam-singularity"
nougat_qa_source: "shub://remiolsen/qaTools-singularity"
nougat_frc_image: "remiolsen-FRCbam-singularity-master.img"
nougat_qa_image: "remiolsen-qaTools-singularity-master.img"

kmer_source: "http://kmergenie.bx.psu.edu"
kmer_dest: "{{ sw_path }}/KmerGenie/"
kmer_version: "kmergenie-1.7039"

frc_align_repo: "https://github.com/vezzi/FRC_align.git"
frc_align_dest: "{{ sw_path }}/FRCAlign"
frc_align_version: "5b3f53e01cb539c857fd4230ec9410d76220fe22"

nougat_repo: "https://github.com/SciLifeLab/NouGAT.git"
nougat_dest: "{{ sw_path }}/NouGAT"
nougat_version: "7e7c7ccc727e0fd5577da32b3f4553a17d819d26"
