---

- name: Fetch CAW from GitHub
  git: repo="{{ caw_repo }}"
       dest="{{ caw_dest }}"
       version="{{ caw_version }}"
       force=yes

- name: Create CAW Singularity folder
  file: name="{{ caw_singularity }}"
        state=directory mode=g+s

- name: Create temp directory for CAW singularity images
  command: "mkdir {{ item }}"
  args:
    creates: "{{ item }}"
  with_items:
  - "{{ caw_singularity }}/singularity_cache"
  - "{{ caw_singularity }}/singularity_temp"

- name: Pull CAW Singularity images
  command: "singularity build {{ item }}-{{ caw_version }}.img {{ caw_singularity_repo }}/{{ item }}:{{ caw_version }}"
  environment:
    SINGULARITY_CACHEDIR: "{{ caw_singularity }}/singularity_cache"
    SINGULARITY_TMPDIR: "{{ caw_singularity }}/singularity_temp"
  args:
    chdir: "{{ caw_singularity }}"
  with_items: "{{ caw_singularity_images }}"

- name: Remove CAW singularity temp directories
  command: "rm -rf {{ item }}" 
  args:
    removes: "{{ item }}"
  with_items:
  - "{{ caw_singularity }}/singularity_cache"
  - "{{ caw_singularity }}/singularity_temp"

- name: Create CAW site config
  template:
    src: "caw_site.config"
    dest: "{{ ngi_pipeline_conf }}/caw_{{ item.site }}.config"
  with_items:
  - { site: "sthlm", project_id: "{{ ngi_pipeline_sthlm_delivery }}", container_path: "{{ caw_singularity }}" }
  - { site: "upps", project_id: "{{ ngi_pipeline_upps_delivery }}", container_path: "{{ caw_singularity }}" }

- name: Set CAW alias
  lineinfile: dest="{{ ngi_pipeline_conf }}/{{ item.script }}"
              line="alias caw='nextflow run {{ caw_dest }}/main.nf -c {{ ngi_pipeline_conf }}/caw_{{ item.site }}.config -profile slurm'"
              backup=no
  with_items:
  - { site: "sthlm", script: "{{ bash_env_sthlm_script }}" }
  - { site: "upps", script: "{{ bash_env_upps_script }}" }
