---

# If deploying to staging one should call with 
# -e deployment_environment=staging
# One can also override the default installed version 
# by overriding the arteria_delivery_version on the command line. 
#
# This will set corresponding paths and use the appropriate port. 
arteria_delivery_repo: https://github.com/arteria-project/arteria-delivery.git
arteria_delivery_version: v2.1.0

arteria_install_path: "{{ sw_path }}/arteria"
conda_bin: "{{ sw_path }}/anaconda/bin/conda"

# These values will be appended with production and staging specific
# paths in the tasks.
#
# NB. The log dirs need to be created manually on destination cluster.
#
# NB 2. Hard coded root path for runfolders, because that path 
# needs to be reachable from outside world; i.e. have to be under /proj
# And hard coded log paths because we do not want the log files 
# to disappear when the wildwest directory is cleaned out with every 
# staging sync. 
arteria_delivery_env_root: "{{ sw_path }}/anaconda/envs/arteria-delivery"
arteria_delivery_sources_path: "{{ arteria_install_path }}/delivery_src"
arteria_delivery_config_root: "{{ ngi_pipeline_conf }}/arteria/delivery"
arteria_delivery_app_config: "{{ arteria_delivery_config_root }}/app.config"
arteria_delivery_logger_config: "{{ arteria_delivery_config_root }}/logger.config"
arteria_delivery_log: "/proj/{{ ngi_pipeline_upps_delivery }}/private/log/arteria/delivery-ws"

runfolder_path_stage: "/proj/{{ ngi_pipeline_upps_delivery }}/incoming/staging"
project_path_stage: "/proj/{{ ngi_pipeline_upps_delivery }}/incoming/staging/projects"
staging_path_stage: "/proj/{{ ngi_pipeline_upps_delivery }}/incoming/staging/staged"

runfolder_path_prod: "/proj/{{ ngi_pipeline_upps_delivery }}/incoming"
project_path_prod: "/proj/{{ ngi_pipeline_upps_delivery }}/nobackup/NGI/DELIVERY"
staging_path_prod: "/proj/{{ ngi_pipeline_upps_delivery }}/nobackup/NGI/DELIVERY/arteria-staged"

db_path_stage: "/proj/{{ ngi_pipeline_upps_delivery }}/private/db/arteria/staging" 
db_path_prod: "/proj/{{ ngi_pipeline_upps_delivery }}/private/db/arteria"
alembic_path: "{{ arteria_delivery_sources_path }}/alembic/"
delivery_links: "/proj/{{ ngi_pipeline_upps_delivery }}/nobackup/arteria/delivery_project_links"

arteria_delivery_port_prod: 10440
arteria_delivery_port_stage: 10441

mover_path: "/usr/local/mover/1.0.0/"
