nextflow_java: "/sw/comp/java/x86_64/sun_jdk1.8.0_151"
nextflow_version_tag: "v20.01.0"
nextflow_download_url: "https://github.com/nextflow-io/nextflow/releases/download/{{ nextflow_version_tag }}/nextflow"
nf_core_env: "/lupus/ngi/irma3/nf-core-env"
pipelines:
  - name: rnaseq
    release: 1.4.2
  - name: methylseq
    release: 1.4
  - name: ampliseq
    release: 1.1.2
  - name: atacseq
    release: 1.1.0
