---

# The steps within the comments can be effectively replaced by 'module load Nextflow'
# Currently the module has problems being automatically initialized
###

- name: Create NextFlow directory
  file: path="{{ nextflow_dest }}" state=directory mode=g+rwXs

- name: Create NextFlow installation subdirectory
  file: path="{{ nextflow_dest }}/workfiles" state=directory mode=g+rwXs

- name: Create NextFlow installation plugins subdirectory
  file: path="{{ nextflow_dest }}/workfiles/plugins" state=directory mode=g+rwXs

- name: Download NextFlow
  get_url: url="{{ nextflow_download_url }}" dest="{{ nextflow_dest }}/nextflow" mode="u+rwx,g=rwx"

# Resolved any problems. Run-time files are pushed to scratch
- name: Install NextFlow
  shell: "./nextflow"
  environment:
    NXF_LAUNCHER: "/scratch"
    NXF_HOME: "{{ nextflow_dest }}/workfiles"
    NXF_WORK: "/scratch"
  args:
    chdir: "{{ nextflow_dest }}"

- name: Grab Nextflow version number
  shell: "ls {{ nextflow_dest }}/workfiles/framework/ | tail -1"
  register: nextflow_ver

- name: Add NextFlow to $PATH
  lineinfile: dest="{{ ngi_pipeline_conf }}/{{ bash_env_script }}"
              line="export PATH={{ root_path }}/sw/nextflow:$PATH"
              backup=no
###

- name: Create irma config
  template:
    src: "nextflow_irma_site.config.j2"
    dest: "{{ ngi_pipeline_conf }}/nextflow_irma_{{ item.site }}.config"
  with_items:
  - { site: "sthlm", project_id: "{{ ngi_pipeline_sthlm_delivery }}" }
  - { site: "upps", project_id: "{{ ngi_pipeline_upps_delivery }}" }

# Change target to {{ ngi_rnaseq_dest }} when using module system
# NXF_WORK is omitted, which puts them under current directory
- name: Add Nextflow module vars to sourceme
  lineinfile: dest={{ ngi_pipeline_conf }}/{{ bash_env_script }}
              line="{{ item.envvar }}"
              backup=no
  with_items:
  - { envvar: "export NXF_OPTS='-Xms1g -Xmx4g'"}
  - { envvar: "export NXF_VER={{ nextflow_ver.stdout }}"}
  - { envvar: "export NXF_HOME={{ nextflow_dest }}/workfiles"}
  - { envvar: "export NXF_LAUNCHBASE=$PWD/work"}
# Defines where the classpath file ends up
  - { envvar: "export NXF_LAUNCHER=$PWD/work"}
# Path to java to be used for nextflow
  - { envvar: "export NXF_JAVA_HOME={{ nextflow_java }}"}

- name: Store nextflow version in deployment
  lineinfile:
    dest: "{{ deployed_tool_versions }}"
    line: "Nextflow: {{ nextflow_ver.stdout }}"
