---

# For now, values here should be updated accordingly when user develops locally. 

# root_path should be changed to suitable value when e.g. deploying locally
# for a developer
root_path: /lupus/ngi/

# TODO: This variable has to be set to something more suitable when 
# deploying as a real user with a real home directory 
home_path: /tmp 

# Name of the script that should be sourced from the user to get the 
# relevant environment variables setup. Perhaps move this to defaults vars.  
bash_env_script: sourceme_common.sh

ngi_pipeline_repo: https://github.com/NationalGenomicsInfrastructure/ngi_pipeline.git
ngi_pipeline_dest: "{{ root_path }}/sw/ngi_pipeline"
ngi_pipeline_version: 8ef4d3632c0d7130aa2766ac62b009c0b834b81b
ngi_pipeline_venv: "{{ root_path }}/sw/anaconda/envs/NGI"

ngi_pipeline_conf: "{{ root_path }}/conf/"
ngi_pipeline_db: "{{ root_path }}/db/"

ngi_pipeline_slurm_project: ngi2016001
ngi_pipeline_sthlm_delivery: ngi2016003
ngi_pipeline_upps_delivery: ngi2016001

ngi_piper_repo: https://github.com/NationalGenomicsInfrastructure/piper.git
ngi_piper_src_dest: "{{ root_path }}/sw/piper_src"
ngi_piper_bin_dest: "{{ root_path }}/sw/piper"
ngi_piper_version: 051ca55f20949279b68fc1c96ce071b117f57a05

# TODO: Where to store API token? How to reach charon-dev, if necessary? 
# charon settings are fetched from charon_credentials.yml for now, 
# that is not checked into repo.  

# TODO: Move these settings to somewhere else? 
gatk_bundle_b37_origin: "/sw/data/uppnex/reference/biodata/GATK/ftp.broadinstitute.org/bundle/2.8/b37/"
gatk_bundle_b37: "{{ root_path }}/piper_resources/gatk_bundle/2.8/b37"
gatk_bundle_hg19: "{{ root_path }}/piper_references/gatk_bundle/2.8/hg19"

gatk_key: pontus.larsson_medsci.uu.se.key

recipient_mail: ngi_pipeline_operators@scilifelab.se
ngi_pipeline_logs: "{{ root_path }}/log/"

taca_ngi_repo: https://github.com/NationalGenomicsInfrastructure/taca-ngi-pipeline.git
taca_ngi_dest: "{{ root_path }}/sw/taca-ngi-pipeline"
taca_ngi_version: 35db8a3fe031c3a69cb7422fcc55d74506a04998
