---
ngi_reports_repo: https://github.com/NationalGenomicsInfrastructure/ngi_reports.git
ngi_reports_dest: "{{ sw_path }}/ngi_reports"
ngi_reports_version: 04147aa73599b8e7394b7b5bb94ae1dd414641e9
ngi_reports_log: "/log/ngi_reports.log"
ngi_reports_log_sthlm: "{{ ngi_pipeline_sthlm_path }}/{{ ngi_reports_log }}"
ngi_reports_log_upps: "{{ ngi_pipeline_upps_path }}/{{ ngi_reports_log }}"

ngi_visual_repo: https://github.com/NationalGenomicsInfrastructure/ngi_visualizations.git
ngi_visual_dest: "{{ sw_path }}//ngi_visualization"
ngi_visual_version: bf1892faf5ebe16ad0979cfc83f9c72b90e2a5a0
