- include: dependencies.yml

- name: Fetch TACA-ngi-pipeline from GitHub
  git: repo="{{ taca_ngi_repo }}"
       dest="{{ taca_ngi_dest }}"
       version="{{ taca_ngi_version }}"
       force=yes

- name: Install TACA-ngi-pipeline requirements
  shell: "{{ ngi_pipeline_venv }}/bin/pip install -r {{ taca_ngi_dest }}/requirements.txt"

- name: Install TACA-ngi-pipeline
  shell: "{{ ngi_pipeline_venv }}/bin/pip install ."
  args: 
    chdir: "{{ taca_ngi_dest }}"

- name: Create TACA delivery configs directory
  file: path="{{ ngi_pipeline_conf }}/TACA" state=directory mode=g+s

- set_fact: 
    site: "upps"
    site_full: "uppsala"
    ngi_pipeline_site_path: "{{ ngi_pipeline_upps_path }}"
    ngi_site_softlinks: "{{ ngi_upps_softlinks }}"
    ngi_pipeline_site_delivery: "{{ ngi_pipeline_upps_delivery }}"
    recipient_mail: "{{ recipient_mail_upps }}"

- name: Deploy standard uppsala configs
  template: src="site_taca_delivery.yml.j2" dest="{{ ngi_pipeline_conf }}/TACA/{{ site }}_{{ item.name }}_delivery.yml"
  with_items:
  - { proj_path: "{{ proj_root }}", name: "lupus" }
  - { proj_path: "{{ milou_delivery_root }}", name: "taca" } 

- set_fact: 
    site: "sthlm"
    site_full: "stockholm"
    ngi_pipeline_site_path: "{{ ngi_pipeline_sthlm_path }}"
    ngi_site_softlinks: "{{ ngi_sthlm_softlinks }}"
    ngi_pipeline_site_delivery: "{{ ngi_pipeline_sthlm_delivery }}"
    recipient_mail: "{{ recipient_mail_sthlm }}"

- name: Deploy sthlm_taca_local.yml config
  template: src="site_taca_local.yml.j2" dest="{{ ngi_pipeline_conf }}/TACA/{{ site }}_taca_local.yml"

- name: Deploy sthlm_fastq_taca_delivery.yml config
  template: src="site_fastq_delivery.yml.j2" dest="{{ ngi_pipeline_conf }}/TACA/{{ site }}_{{ item.name }}_fastq_delivery.yml"
  with_items:
  - { proj_path: "{{ proj_root }}", name: "lupus" }
  - { proj_path: "{{ milou_delivery_root }}", name: "taca" }

- name: Deploy standard stockholm configs
  template: src="site_taca_delivery.yml.j2" dest="{{ ngi_pipeline_conf }}/TACA/{{ site }}_{{ item.name }}_delivery.yml"
  with_items:
  - { proj_path: "{{ proj_root }}", name: "lupus" }
  - { proj_path: "{{ milou_delivery_root }}", name: "taca" }

- name: Deploy RNABP stockholm configs
  template: src="site_rna_delivery.yml.j2" dest="{{ ngi_pipeline_conf }}/TACA/{{ site }}_{{ item.name }}_rna_delivery.yml"
  with_items:
  - { proj_path: "{{ proj_root }}", name: "lupus" }
  - { proj_path: "{{ milou_delivery_root }}", name: "taca" }
