---
- name: Fetch non-SciLifeLab repos from GitHub
  git: repo="{{ item.repo }}"
       dest="{{ item.dest }}"
       version="{{ item.version }}"
  with_items:
# commented this out as the defaults were commented out for this tool
#  -  { repo: "{{ qatools_repo }}", dest: "{{ qatools_dest }}", version: "{{ qatools_version }}" }
  -  { repo: "{{ frc_align_repo }}", dest: "{{ frc_align_dest }}", version: "{{ frc_align_version }}" }

- name: Create FRC_Align build directory
  file: path="{{ frc_align_dest }}/build" state=directory mode=g+rwxs

- name: Make FRC_Align
  shell: "module load boost && cmake .."
  args: 
    chdir: "{{ frc_align_dest }}/build"
    creates: "{{ frc_align_dest }}/LICENSE"  

- name: Fetch KmerGenie
  get_url:
    url: "{{ kmer_source }}/{{ kmer_version }}.tar.gz"
    dest: "/scratch/{{ kmer_version }}.tar.gz"

- name: Unpack KmerGenie
  unarchive:
    src: "/scratch/{{ kmer_version }}.tar.gz"
    dest: "/scratch/"
    copy: no
    mode: g+rwxs

- name: Create KmerGenie installation directory
  command: mv "/scratch/{{ kmer_version }}" "{{ kmer_dest }}"
  args:
    creates: "{{ kmer_dest }}"
    removes: "/scratch/{{ kmer_version }}"

- name: Install Kmergenie
  shell: "make"
  args:
    chdir: "{{ kmer_dest }}"

- name: Fix KmerGenie permission issue
  file:
    path: "{{ kmer_dest }}/kmergenie"
    state: touch
    mode: "u+rwx"

- name: Add KmerGenie to $PATH
  lineinfile: dest={{ ngi_pipeline_conf }}/{{ bash_env_script }}
              line='export PATH={{ kmer_dest }}:$PATH'
              backup=no

- name: create nougat singularity
  file: name={{ nougat_singularity_dest }} state=directory mode=g+s

- name: Download Sigularity image
  command: singularity pull "{{ item }}"
  args:
    chdir: "{{ nougat_singularity_dest }}"
  with_items:
    - "{{ nougat_frc_image }}"
    - "{{ nougat_qa_image }}"

#- name: Install Kmergenie
#  shell: "{{ ngi_pipeline_venv }}/bin/pip install -e ."
#  args:
#    chdir: "{{ kmer_dest }}/{{ kmer_version }}"

#TODO: Omitted for now due to complications. Removed completely in a later version (if decided ofc ;) ) 
#- name: Make qaTools
#  shell: "make -f {{ qatools_dest }}/Makefile SAMTOOLS=/sw/apps/bioinfo/samtools/0.1.19/src/"
#  args:
#    chdir: "{{ qatools_dest }}"
#    creates: "{{ qatools_dest }}/LICENSE"
