---
- include: dependencies.yml

- name: Fetch NouGAT from GitHub
  git: repo="{{ nougat_repo }}"
       dest="{{ nougat_dest }}"
       version="{{ nougat_version }}"
       force=yes

- name: Install NouGAT's requirements
  shell: "{{ ngi_pipeline_venv }}/bin/pip install -r {{ nougat_dest }}/requirements.txt"

- name: Copy configuration
  template: src="NouGAT_config.conf.j2" dest="{{ ngi_pipeline_conf }}/NouGAT_config.conf"

- name: Install NouGAT
  shell: "{{ ngi_pipeline_venv }}/bin/pip install -e ."
  args:
    chdir: "{{ nougat_dest }}"

- name: Add NOUGAT_CONF envvar to sthlm_sourceme 
  lineinfile: dest={{ ngi_pipeline_conf }}/{{ bash_env_sthlm_script }}
              line="export NOUGAT_CONF={{ ngi_pipeline_conf }}/NouGAT_config.conf"
              backup=no

- name: Store nougat tool version in deployment
  lineinfile:
    dest: "{{ deployed_tool_versions }}"
    line: "{{ item.tool_name }}: {{ item.tool_version }}"
  with_items:
    - { tool_name: "NouGAT", tool_version: "{{ nougat_version }}" }
    - { tool_name: "KmerGenie", tool_version: "{{ kmer_version }}" }
    - { tool_name: "FRC_align", tool_version: "{{ frc_align_version }}" }
