---

- name: Copy R dependencies script
  copy:
    src: "files/install_R_dependencies.r"
    dest: "{{ ngi_rnaseq_dest }}/r_packages"

- name: Run R script to install dependencies
  command: "Rscript install_R_dependencies.r"
  environment:
    R_LIBS_USER: "{{ ngi_rnaseq_dest }}/r_packages"
  args:
    chdir: "{{ nextflow_dest }}/r_packages"

- name: Fetch NGI-RNAseq from GitHub
  git: repo="{{ ngi_rnaseq_repo }}"
       dest="{{ ngi_rnaseq_dest }}"
       version="{{ ngi_rnaseq_version }}"
       force=yes

- name: Create NGI-RNAseq config
  template:
    src: "ngi-rnaseq_site.config"
    dest: "{{ ngi_pipeline_conf }}/ngi-rnaseq_{{ item.site }}.config"
  with_items:
  - { site: "sthlm", project_id: "{{ ngi_pipeline_sthlm_delivery }}" }
  - { site: "upps", project_id: "{{ ngi_pipeline_upps_delivery }}" }


- name: Set alias
  lineinfile: dest="{{ ngi_pipeline_conf }}/{{ item.script }}"
              line="alias rnaseq='nextflow {{ ngi_rnaseq_dest }}/main.nf -c {{ ngi_pipeline_conf }}/ngi-rnaseq_{{ item.site }}.config'"
              backup=no
  with_items:
  - { site: "sthlm", script: "{{ bash_env_sthlm_script }}" }
  - { site: "upps", script: "{{ bash_env_upps_script }}" }
