---

- name: Fetch NGI-RNAseq from GitHub
  git: repo="{{ ngi_rnaseq_repo }}"
       dest="{{ ngi_rnaseq_dest }}"
       version="{{ ngi_rnaseq_version }}"
       force=yes

- name: Create NGI-RNAseq temp/cache folder for images
  file: name="{{ item }}" state=directory mode=g+s
  with_items:
  - "{{ ngi_rnaseq_singularity_path }}/singularity_cache"
  - "{{ ngi_rnaseq_singularity_path }}/singularity_temp"

- name: Pull NGI-RNAseq Singularity images
  command: "singularity build {{ ngi_rnaseq_image }} {{ ngi_rnaseq_singularity_url }}"
  environment:
    SINGULARITY_CACHEDIR: "{{ ngi_rnaseq_singularity_path }}/singularity_cache"
    SINGULARITY_TMPDIR: "{{ ngi_rnaseq_singularity_path }}/singularity_temp"
  args:
    chdir: "{{ ngi_rnaseq_singularity_path }}"

- name: Remove NGI-RNAseq singularity temp directories
  file: name="{{ item }}" state=absent
  with_items:
  - "{{ ngi_rnaseq_singularity_path }}/singularity_cache"
  - "{{ ngi_rnaseq_singularity_path }}/singularity_temp"

- name: Create NGI-RNAseq config
  template:
    src: "ngi-rnaseq_site.config"
    dest: "{{ ngi_pipeline_conf }}/ngi-rnaseq_{{ item.site }}.config"
  with_items:
  - { site: "sthlm", project_id: "{{ ngi_pipeline_sthlm_delivery }}" }
  - { site: "upps", project_id: "{{ ngi_pipeline_upps_delivery }}" }

- name: Set alias for NGI-RNAseq
  lineinfile: dest="{{ ngi_pipeline_conf }}/{{ item.script }}"
              line="alias rnaseq='nextflow run {{ ngi_rnaseq_dest }}/main.nf -c {{ ngi_pipeline_conf }}/ngi-rnaseq_{{ item.site }}.config -profile uppmax'"
              backup=no
  with_items:
  - { site: "sthlm", script: "{{ bash_env_sthlm_script }}" }
  - { site: "upps", script: "{{ bash_env_upps_script }}" }
