---
- name: Fetch MultiQC from GitHub
  git: repo="{{ multiqc_repo }}"
       dest="{{ multiqc_dest }}"
       version="{{ multiqc_version }}"
       force=yes

#Remember to use --upgrade flag if using commit-id
#Using the python3 env
- name: Temporarily fix matplotlib at v3.2.2 to get rid of warnings
  pip:
    name: matplotlib
    version: 3.2.2
    executable: "{{ sw_path }}/anaconda/envs/{{ NGI_venv_py3_name }}/bin/pip"

- name: Install MultiQC
  pip:
    name: "file:{{ multiqc_dest }}"
    virtualenv: "{{ sw_path }}/anaconda/envs/{{ NGI_venv_py3_name }}"

- name: Fetch MultiQC NGI plugin from GitHub
  git: repo="{{ multiqc_ngi_repo }}"
       dest="{{ multiqc_ngi_dest }}"
       version="{{ multiqc_ngi_version }}"
       force=yes

#Remember to use --upgrade flag if using commit-id
#Using the python3 env
- name: Install MultiQC NGI submodule
  pip:
    name: "file:{{ multiqc_ngi_dest }}"
    virtualenv: "{{ sw_path }}/anaconda/envs/{{ NGI_venv_py3_name }}"

- name: Deploy multiqc configs
  template: src="multiqc_config.yml.j2" dest="{{ ngi_pipeline_conf }}/multiqc_{{ item.site }}_config.yml"
  with_items:
  - { site: "sthlm", disable_ngi_hooks: "False"}
  - { site: "upps", disable_ngi_hooks: "True"}

- name: Force multiqc to autorun config
  lineinfile: dest="{{ ngi_pipeline_conf }}/{{ item.script }}"
              line="alias multiqc='{{ sw_path }}/anaconda/envs/{{ NGI_venv_py3_name }}/bin/multiqc -c {{ ngi_pipeline_conf }}/multiqc_{{ item.site }}_config.yml {{ item.flags }}'"
              backup=no
  with_items:
  - { site: "sthlm", script: "{{ bash_env_sthlm_script }}", flags: ""}
  - { site: "upps", script: "{{ bash_env_upps_script }}", flags: "" }

- name: Store MultiQC tool version in deployment
  lineinfile:
    dest: "{{ deployed_tool_versions }}"
    line: "{{ NGI_venv_py3_name }}, {{ item.tool_name }}: {{ item.tool_version }}"
  with_items:
    - { tool_name: "MultiQC", tool_version: "{{ multiqc_version }}" }
    - { tool_name: "MultiQC_NGI", tool_version: "{{ multiqc_ngi_version }}" }
